version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatgpt_db
      - MONGO_DB_NAME=chatgpt_db
      - SECRET_KEY=your_secret_key_here
      - OLLAMA_API_URL=http://host.docker.internal:11434
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  mongo:
    image: mongo:4.4-bionic
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chatgpt_db

volumes:
  mongo-data: